name: Run ubpf vm tests

on:
  push:
    branches: "master"
  pull_request: 
    branches: "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake make clang-15 ninja-build
    - name: Build targets
      run: |
        CC=clang-15 CXX=clang++-15 cmake -S. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja
        CC=clang-15 CXX=clang++-15 cmake --build ./build --config Release --target libebpf_test_runner
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - run: python --version
    - run: |
        cd vm-test
        python -m venv env
        source ./env/bin/activate
        pip install -r requirements.txt
        pytest
