name: Run unit tests of ebpf_state

on:
  push:
    branches: "master"
  pull_request: 
    branches: "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake make clang-15 ninja-build 
    - name: Build targets
      run: |
        CC=clang-15 CXX=clang++-15 cmake -S. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja
        CC=clang-15 CXX=clang++-15 cmake --build ./build --config Release --target ebpf_state_test
    - name: Run tests
      run: |
        ./build/execution-test/ebpf_state_test
